# Generated by Django 4.1.1 on 2022-10-01 20:35

import apps.files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_file_path_alter_file_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to=apps.files.models.get_path),
        ),
        migrations.AlterField(
            model_name="file",
            name="file_name",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
