# Generated by Django 4.1.1 on 2022-10-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_file_file_alter_file_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.CharField(default='', max_length=100),
        ),
    ]
